namespace DomainGateway.ServiceDiscovery.Client.Configuration;

public record ServiceDiscoveryConfiguration(ServiceDiscoveryClientConfiguration Client, ServiceDiscoveryRegistryConfiguration? Registry);
