@baseUrl = https://localhost:5001

###################
### info route - direct
###################
GET {{baseUrl}}/info
Accept: application/json
Client-Id: test-client

###################
### info route - proxied
###################
GET {{baseUrl}}/proxied/info
Accept: application/json
Client-Id: test-client

###################
### http exchangerate route - proxied
###################
GET {{baseUrl}}/api/exchangerate
Accept: application/json
Client-Id: test-client

###################
### http exchangerate route - proxied with request parameter
###################
GET {{baseUrl}}/api/exchangerate?fromCurrency=USD
Accept: application/json
Client-Id: test-client

###################
### grpc route - proxied
### exchangerateservice.Exchangerate/GetRate
### grpcurl -plaintext -d '{"fromCurrency":"USD"}' localhost:6000 exchangerateservice.Exchangerate/GetRate
###################
GRPC localhost:5010/softeering.ExchangeRate/GetRate
Client-Id: test-client

{
    "fromCurrency": "EUR"
}
