@baseUrl = https://localhost:5001
@testService = service-test

###################
### Servcie discovery - register instance
###################
POST {{baseUrl}}/servicediscovery/{{testService}}/register
Content-Type: application/json
Client-Id: test-client

{
  "serviceName": "{{testService}}",
  "instanceId": "instance-1",
  "serviceVersion": "1.0.0",
  "host": "localhost",
  "port": 6000,
  "metadata": {
    "az": "us-east-1a"
  }
}

###################
### Servcie discovery - list instances
###################
GET {{baseUrl}}/servicediscovery/{{testService}}/instances
Accept: application/json
Client-Id: test-client

###################
### Servcie discovery - heartbeat
###################
PUT {{baseUrl}}/servicediscovery/{{testService}}/ping
Content-Type: application/json
Client-Id: test-client

{
  "serviceName": "{{testService}}",
  "instanceId": "instance-1",
  "serviceVersion": "1.0.1",
  "host": "localhost",
  "port": 6000,
  "metadata": {
    "az": "us-east-1a"
  }
}

###################
### Servcie discovery - re-register
###################
DELETE {{baseUrl}}/servicediscovery/{{testService}}/instance-1
Client-Id: test-client
