// <auto-generated />
using System;
using DomainGateway.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DomainGateway.Database.Migrations
{
    [DbContext(typeof(DomainGatewayDbContext))]
    [Migration("20251102140711_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DomainGateway.ServiceDiscovery.ServiceInstanceEntity", b =>
                {
                    b.Property<string>("ServiceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RegistrationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceVersion")
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceName", "InstanceId");

                    b.HasIndex("ServiceName");

                    b.ToTable("Instances");
                });
#pragma warning restore 612, 618
        }
    }
}
